{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bin-notifier.fullname" . }}-api
  labels: {{- include "bin-notifier.labels" . | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  {{- if .Values.api.ingress.tls.enabled }}
  tls:
    - hosts: [{{ .Values.api.ingress.host | quote }}]
      secretName: {{ .Values.api.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bin-notifier.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
