{{- if not .Values.existingTokensSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bin-notifier.tokensSecretName" . }}
  labels: {{- include "bin-notifier.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  read-token: {{ .Values.tokens.readToken | default (randAlphaNum 40) | quote }}
  write-token: {{ .Values.tokens.writeToken | default (randAlphaNum 40) | quote }}
{{- end }}
